<?xml version="1.0"?>
<definitions name="HelloWorld" targetNamespace="urn:HelloWorld" xmlns:tns="urn:HelloWorld"  xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/">
    <types>
        <xsd:schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Test">
            <xsd:element name="dataType" type="xsd:integer" />
            <xsd:element name="ETBResponse" type="xsd:string" />
        </xsd:schema>
    </types>

    <message name="ETB">
        <part name="yourValue" type="tns:dataType" />
    </message>

    <message name="ETBResponse">
        <part name="return" type="tns:dataType" />
    </message>

    <portType name="ConvertPort">
        <operation name="ETB">
            <input message="tns:ETB" />
            <output message="tns:ETBResponse" />
        </operation>
    </portType>

    <binding name="bind" type="tns:ConvertPort">
        <operation name="ETB">
            <soap:operation soapAction="urn:ConvertAction" />
            <input>
                <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
            </input>
            <output>
                <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
            </output>
        </operation>
    </binding>



    <service name="Service">
        <port name="ConvertPort" binding="tns:bind">
            <soap:address location="http://rnwa.test/EurToBam.php"/>
        </port>
    </service>

</definitions>