//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsreWebService.Service {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.WebServis1Soap")]
    public interface WebServis1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/konverzijaBAMToEUR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        float konverzijaBAMToEUR(float bam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/konverzijaBAMToEUR", ReplyAction="*")]
        System.Threading.Tasks.Task<float> konverzijaBAMToEURAsync(float bam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/konverzijaEURToBAM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        float konverzijaEURToBAM(float eur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/konverzijaEURToBAM", ReplyAction="*")]
        System.Threading.Tasks.Task<float> konverzijaEURToBAMAsync(float eur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCustomerByCustomerNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getCustomerByCustomerNumber(string customerNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCustomerByCustomerNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getCustomerByCustomerNumberAsync(string customerNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEmployeeByEmployeeNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getEmployeeByEmployeeNumber(string employeeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEmployeeByEmployeeNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getEmployeeByEmployeeNumberAsync(string employeeNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServis1SoapChannel : FsreWebService.Service.WebServis1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServis1SoapClient : System.ServiceModel.ClientBase<FsreWebService.Service.WebServis1Soap>, FsreWebService.Service.WebServis1Soap {
        
        public WebServis1SoapClient() {
        }
        
        public WebServis1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServis1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServis1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServis1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float konverzijaBAMToEUR(float bam) {
            return base.Channel.konverzijaBAMToEUR(bam);
        }
        
        public System.Threading.Tasks.Task<float> konverzijaBAMToEURAsync(float bam) {
            return base.Channel.konverzijaBAMToEURAsync(bam);
        }
        
        public float konverzijaEURToBAM(float eur) {
            return base.Channel.konverzijaEURToBAM(eur);
        }
        
        public System.Threading.Tasks.Task<float> konverzijaEURToBAMAsync(float eur) {
            return base.Channel.konverzijaEURToBAMAsync(eur);
        }
        
        public System.Data.DataTable getCustomerByCustomerNumber(string customerNumber) {
            return base.Channel.getCustomerByCustomerNumber(customerNumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getCustomerByCustomerNumberAsync(string customerNumber) {
            return base.Channel.getCustomerByCustomerNumberAsync(customerNumber);
        }
        
        public System.Data.DataTable getEmployeeByEmployeeNumber(string employeeNumber) {
            return base.Channel.getEmployeeByEmployeeNumber(employeeNumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getEmployeeByEmployeeNumberAsync(string employeeNumber) {
            return base.Channel.getEmployeeByEmployeeNumberAsync(employeeNumber);
        }
    }
}
